name: Terraform EC2 Provisioning

on:
  workflow_dispatch:  # Manual trigger (you can run the workflow manually)

jobs:
  terraform:
    name: Provision EC2 with Terraform
    runs-on: ubuntu-latest  # Using the latest Ubuntu runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Check out your repository

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Fetch from GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Fetch from GitHub Secrets
          aws-region: eu-central-1  # Set your AWS region

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Set the Terraform version (or latest stable version)

      - name: Terraform Init
        run: terraform init  # Initialize Terraform configuration
        working-directory: infra  # Ensure this matches the directory containing your .tf files

      - name: Terraform Format Check
        run: terraform fmt -check  # Check if files are correctly formatted
        working-directory: infra  # Ensure this matches the directory containing your .tf files

      - name: Terraform Validate
        run: terraform validate  # Validate the Terraform configuration
        working-directory: infra  # Ensure this matches the directory containing your .tf files

      - name: Terraform Plan
        run: terraform plan  # Show the execution plan for provisioning resources
        working-directory: infra  # Ensure this matches the directory containing your .tf files

      - name: Terraform Apply
        run: terraform apply -auto-approve  # Apply the Terraform configuration automatically
        working-directory: infra  # Ensure this matches the directory containing your .tf files
