name: Terraform Format Check

on:
  pull_request:
    paths:
      - '**/*.tf'
  push:
    paths:
      - '**/*.tf'

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.4.0'

      - name: Terraform Format Check
        run: terraform fmt -check -diff
